### ISSUE TITLE
Remote Debugging - DEVTRON_DEBUG_PATH

### ISSUE THREAD

**Issue by nvcwk** [electron/devtron#84]
For remote debugging, this was mentioned:  

> Set the DEVTRON_DEBUG_PATH environment variable to the path of the cloned devtron repository. 

As I am new to environment variable, could you please show me exactly how to incorporate "DEVTRON_DEBUG_PATH" into the Command-Line Interface or Main.js (the starting JS file for Electron)? 

Thank you for your help.

**Comment by kevinsawicki** [comment]
`DEVTRON_DEBUG_PATH` is only for when you are developing devtron locally.

Are you tweaking the devtron source code locally?

If not, you don't need to worry about this environment variable since it is only useful when you are making fixes or enhancements to devtron itself.

You can set it on the command line using something like `export DEVTRON_DEBUG_PATH=/Users/kevin/github/devtron`
